blueprint:
  name: AWTRIX playing now
  description: Show the current playing track
  domain: automation
  input:
    media_player:
      name: Media player
      description: Media player what you want to control.
      selector:
        entity:
          filter:
            - domain: media_player
          multiple: false

    awtrix_device:
      name: AWTRIX device
      description: The AWTRIX device for show playing status.
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX Light
          multiple: false

trigger:
  - platform: state
    entity_id: !input media_player
    id: player

  - platform: time_pattern
    seconds: '/10'
    id: timer

condition:
  - condition: or
    conditions:
      - condition: trigger
        id:
          - player
      - condition: and
        conditions:
          - condition: trigger
            id:
              - timer
          - condition: template
            value_template: "{{ states(media_player_device) == 'playing' }}"

variables:
  awtrix: !input awtrix_device
  awtrix_device_name: "{{ iif( device_attr(awtrix, 'name_by_user') != none, device_attr(awtrix, 'name_by_user'), device_attr(awtrix, 'name') ) }}"
  media_player_device: !input media_player

action:
  - variables:
      playing_state: "{{ states(media_player_device) }}"
      title_template: "{{ state_attr(media_player_device, 'media_title') }}"
      album_template: "{{ state_attr(media_player_device, 'media_album_name') }}"
      artist_template: "{{ state_attr(media_player_device, 'media_artist') }}"
      playing_percent: "{{ (100 - ((state_attr(media_player_device, 'media_duration') | default(0, true) - (state_attr(media_player_device, 'media_position') | default(0, true) + as_timestamp(now()) - as_timestamp(state_attr(media_player_device, 'media_position_updated_at') | default(now(), true)))) / 60) * 100 / (state_attr(media_player_device, 'media_duration') | default(1, true)  / 60)) | int }}"

  - if:
      - condition: template
        value_template: "{{ playing_state != 'playing' }}"
    then:
      - service: awtrix.{{awtrix_device_name}}_push_app_data
        data:
          name: sonos
          data: {}
    else:
      - service: awtrix.{{awtrix_device_name}}_push_app_data
        data:
          name: sonos
          data:
            rainbow: false
            repeat: 1
            pushIcon: 0
            textCase: 0
            progress: "{{playing_percent}}"
            progressC: "18B04C"
            progressBC: "#333333"
            text: >-
              {{ playing_state~': '~(artist_template ~ ' - ' if artist_template else '') ~ (title_template if title_template else '-') ~ (' รท ' ~ album_template ~ ' รท ' if album_template else '') }}
            icon: >-
              /9j/4AAQSkZJRgABAgEASABIAAD/4QDKRXhpZgAATU0AKgAAAAgABgESAAMAAAABAAEAAAEaAAUAAAABAAAAVgEbAAUAAAABAAAAXgEoAAMAAAABAAIAAAITAAMAAAABAAEAAIdpAAQAAAABAAAAZgAAAAAAAABIAAAAAQAAAEgAAAABAAeQAAAHAAAABDAyMjGRAQAHAAAABAECAwCgAAAHAAAABDAxMDCgAQADAAAAAQABAACgAgAEAAAAAQAAAAigAwAEAAAAAQAAAAikBgADAAAAAQAAAAAAAAAAAAD/wAARCAAIAAgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9sAQwABAQEBAQECAQECAwICAgMEAwMDAwQGBAQEBAQGBwYGBgYGBgcHBwcHBwcHCAgICAgICQkJCQkLCwsLCwsLCwsL/9sAQwECAgIDAwMFAwMFCwgGCAsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsL/90ABAAB/9oADAMBAAIRAxEAPwD8R/2bvjdd/sOeKvhP+zJqHjTwH8P9Obw7b+NfHviPT7aPVtQ1VPtF/fQ6O93AsscjyafLAISAHAbNrNKHhjn/AF+/4fO/8E1f+ikf+UfVf/kOv42v2vf+Sr6T/wBiT4H/APUc02vl6v5qxnA+Azmnh82xLcataCnO0KTvKUpNu86c5dbJc1lFJLY/Z8NxPi8tnWwFFXp05csbyqKyikkrRnFeb01bbe5//9k=
            lifetime: 900
